config/routes.rb
Wolframpant::Application.routes.draw do
  devise_for :users
  resources :interests
  resources :events
  resources :images, only: [:show, :index, :new, :create, :destroy]
  resources :evints, only: [:new, :create, :destroy, :index]
  resources :projects, only: [:index, :edit, :update, :new, :create]
  resources :projectimages, only: [:show, :index, :new, :create, :destroy]
  get "welcome/index"
  root to: "welcome#index"
  # for resume
  get "welcome/readpdf"
end

app/models/event.rb
class Event < ActiveRecord::Base
 
  has_many :evints
  has_many :images
  has_many :interests, through: :evints
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  # Most of this is here just in case I decide to code in adding and deleting events from the app itself; at this
  # point they're all entered in final form in db.seeds   
  
  def new
    @event = Event.new
    authorize @event
  end
  
  def create
    @event = Event.new(event_params)
    authorize @event
    if @event.save
      flash[:notice] = 'You have successfully added an event.'
      redirect_to :back
    else
      flash[:notice] = 'Please try again.'
      render :new
    end
  end
  
  # edit and update are available from the app, for current_user (myself) only
  
  def edit
    @event = Event.find(params[:id])
    @image = Image.new
    authorize @event
  end
  
  def update
    @event = Event.find(params[:id])
    @image = Image.new
    authorize @event
    if @event.update_attributes(event_params)
      redirect_to edit_event_path(:id => @event.id)
      flash[:notice] = "Success!"
    else
      render :edit
      flash[:notice] = "Please try again."
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    authorize @event
    
    if @event.destroy
      flash[:notice] = "Your event has been removed."
      redirect_to root
    else
      flash[:error] = "Event couldn't be deleted. Please try again."
      redirect_to @event
    end
  end
  
  def show
    @event = Event.find(params[:id])
   # @interests = @event.interests
    @images = @event.images
    @image = Image.new
  end
  
  def index
    @events = Event.all
  end
    
  private
    
  def event_params
    params.require(:event).permit(:name, :description)
  end
    
end

app/views/events/edit.html.haml
%h1 Edit Event #{@event.name}

%p= link_to "Back to Event", @event

= form_for @event do |f|
  = f.label :name
  = f.text_field :name, size: 50
  %br
  %br
  = f.label :description
  %br
  = f.text_area :description, :cols => 120, :rows => 10
  %br
  %br
  = f.submit "Submit"
  
= form_for @image, :html => {:multipart => true} do |f|
  = f.label "Name (optional)"
  = f.text_area :name, size: 50
  %br
  = f.file_field :location
  %br
  %br
  = f.label :prime
  = f.radio_button(:prime, true)
  %br
  = f.label 'not prime'
  = f.radio_button(:prime, false)
  %br
  = f.hidden_field :event_id, :value => @event.id
  = f.submit "Submit"

- if @event.images.exists?
  - @event.images.each do |i|
    .grayscale
      .eventimg
        .high
          = i.name
          = i.prime
        %br
        = image_tag(i.location.full.url)

app/views/events/index.html.haml
%h1 Events

- @events.each do |e|
  = link_to e.name, edit_event_path(e.id)
  %br
  %br

app/views/events/new.html.haml
.container
  %h1 Add Event
  - form_for @event do |f|
    = f.label :name
    = f.text_field :name
    %br
    $br
    = f.label :description
    = f.text_area :description, cols: 120, rows: 10
    %br
    %br
    = f.submit 'Submit'

app/views/events/show.html.haml
.container
  
  .event
    %h2= @event.name
    %p= @event.description
    -if current_user
      = link_to "Add Event", new_event_path
      = link_to "Edit Event", edit_event_path(:id => @event.id)
     
  .images
    - if current_user
      %h3 Add Image for #{@event.name}
      = form_for @image do |f|
        = f.label :name
        = f.text_field :name, :size => 50
        %br
        %br
        = f.label :image
        = f.file_field :location
        = f.hidden_field :location_cache 
        %br
        = f.hidden_field :event_id, :value => @event.id
        %br
        = f.label :prime
        = f.radio_button(:prime, true)
        %br
        = f.label 'not prime'
        = f.radio_button(:prime, false)
        %br
        %br
        = f.submit 'Submit'
        %br
    
    -if @images.exists?
      - @images.each do |pic|
        .eventimg
          = image_tag(pic.location.full.url)
          - if current_user
            = link_to "Delete", image_path(:id => pic.id), :action => 'destroy', :method => :delete, data: {confirm: 'Do you want to delete this image?'}
              
              
              
              
              
              
              
              
              
              
              
              
              