config/routes.rb
Wolframpant::Application.routes.draw do
  devise_for :users
  resources :interests
  resources :events
  resources :images, only: [:show, :index, :new, :create, :destroy]
  resources :evints, only: [:new, :create, :destroy, :index]
  resources :projects, only: [:index, :edit, :update, :new, :create]
  resources :projectimages, only: [:show, :index, :new, :create, :destroy]
  get "welcome/index"
  root to: "welcome#index"
  # for resume
  get "welcome/readpdf"
end

app/models/interest.rb
class Interest < ActiveRecord::Base
  
  has_many :evints
  has_many :events, through: :evints
  
  # for uploading Interest Photos (as distinct from Event Images), using Carrierwave
  mount_uploader :photo, PhotoUploader
  
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController

  def new
    @interest = Interest.new
    authorize @interest
  end
  
  def create
    @interest = Interest.new(interest_params)
    authorize @interest
    if @interest.save
      flash[:notice] = 'You have successfully added an interest.'
      redirect_to :back
    else
      flash[:notice] = 'Please try again.'
      render :new
    end
  end
  
  def edit
    @interest = Interest.find(params[:id])
    authorize @interest
  end
  
  def update
    @interest = Interest.find(params[:id])
    authorize @interest
    if @interest.update_attributes(interest_params)
      redirect_to interest_path
      flash[:notice] = "Success!"
    else
      render :edit
      flash[:notice] = "Please try again."
    end
  end
  
  def destroy
    @interest = Interest.find(params[:id])
    authorize @interest
    
    if @interest.destroy
      flash[:notice] = "Your interest has been removed."
      redirect_to root
    else
      flash[:error] = "Interest couldn't be deleted. Please try again."
      redirect_to @interest
    end
  end
  
  def show
    @interest = Interest.find(params[:id])
    # form for new evints (event/interest relationships) on interests/show page
    @evint = Evint.new
    @events = Event.all
    @evints = @interest.evints
  end
  
  def index
    @interests = Interest.all
  end
    
  private
    
    def interest_params
      params.require(:interest).permit(:name, :description, :photo)
    end
    
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/edit.html.haml
.container
  = form_for @interest do |f|
    = f.label :name
    = f.text_field :name, :size => 50
    %br
    = f.label :description
    %br
    = f.text_area :description, cols: 120, rows: 10
    %br
    -# each Interest has one Photo attribute (Events have many Images)
    %p Add Interest Photo 
    = f.label :photo
    = f.file_field :photo
    = f.hidden_field :photo_cache
    %br
    = f.submit 'Submit'

app/views/interests/new.html.haml
.container
  %h1 Add Interest
  = form_for @interest do |f| 
    = f.label :name 
    = f.text_field :name, :size => 50 
    %br 
    %br 
    = f.label :description 
    %br 
    = f.text_area :description, cols: 120, rows: 10 
    %br 
    %br 
    = f.submit 'Submit' 

app/views/interests/show.html.haml
.container
  .row
    .col-xs-7
      %h3 Related Highlights
      - @evints.each do |e|
        .grayscale
          .inteventimg
            .high
              = link_to e.event.name, e.event
            - if (e.event.images.exists?)
              = link_to image_tag(e.event.images.find_by(:prime => true).location.full.url), e.event
            %br
            - if current_user 
              = link_to "Delete #{e.id}", e, :method => :delete, data: {:confirm => 'Are you sure?'}

    .col-xs-5
      %h2= @interest.name
      %p= @interest.description
      %br
      // only someone logged in as a registered user may add or edit interests, or add events to an interest
      - if current_user
        = link_to 'Edit Interest', edit_interest_path(:id => @interest.id)
        = link_to 'Add Interest', new_interest_path
        %p Add Events
        = form_for @evint do |f|
          = f.collection_select :event_id, @events, :id, :name, size: 50 
          = f.hidden_field :interest_id, :value => @interest.id
          = f.submit 'Save'
        
     
    