config/routes.rb
Wolframpant::Application.routes.draw do
  devise_for :users
  resources :interests
  resources :events
  resources :images, only: [:show, :index, :new, :create, :destroy]
  resources :evints, only: [:new, :create, :destroy, :index]
  resources :projects, only: [:index, :edit, :update, :new, :create]
  resources :projectimages, only: [:show, :index, :new, :create, :destroy]
  get "welcome/index"
  root to: "welcome#index"
  # for resume
  get "welcome/readpdf"
end

app/models/project.rb
class Project < ActiveRecord::Base
 
  has_many :projectimages
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  # for Portfolio page
  
  def index
    @projects = Project.all
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    authorize @project
    if @project.create
      flash[:notice] = 'You have successfully added a project.'
      redirect_to :back
    else
      flash[:notice] = 'Please try again.'
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
    @projectimage = Projectimage.new
    authorize @project
  end
  
  def update
    @project = Project.find(params[:id])
    authorize @project
    if @project.update_attributes(project_params)
      redirect_to projects_path
      flash[:notice] = "Success!"
    else
      render :edit
      flash[:notice] = "Please try again."
    end
  end

  private
  
    def project_params
      params.require(:project).permit(:name, :url, :description)
    end    
  
end

app/views/projects/edit.html.haml
.container
  %h1 Edit Project #{@project.name}

  %p= link_to "Back to Projects", projects_path

  = form_for @project do |f|
    = f.label :name
    = f.text_field :name, size: 50
    %br
    %br
    = f.label :description
    %br
    = f.text_area :description, cols: 100, rows: 3
    = f.label :url
    %br
    = f.text_field :url, size: 50
    %br
    %br
    = f.submit "Submit"
  %br
  %h3 Add Image
  = form_for @projectimage, :html => {:multipart => true} do |f|
    = f.label "Name (optional)"
    = f.text_field :name, size: 50
    %br
    = f.file_field :location
    %br
    = f.hidden_field :project_id, :value => @project.id
    = f.submit "Submit"

app/views/projects/index.html.haml
.container

  %h2 Portfolio
  - if current_user
    = link_to "Add Project", new_project_path
    %br
    %br
  - @projects.each do |p|
    .project
      = link_to p.name, p.url, :target => "_blank" 
      %small (Click on project name to go to live app)
      %br
      = p.description
      - # Only the developer should have a sign-in; current_user will then refer to the developer
      - if current_user
        = link_to "Edit", edit_project_path(id:p.id)
    %br
    - if p.projectimages.exists?
      - # container for all of a project's images
      .projectimg
        - p.projectimages.each do |i|
          - # container for each image
          .projectimage
            = link_to image_tag(i.location.full.url), projectimage_path(:id => i.id)
            = i.name
            - # Only the developer should have a sign-in; current_user will then refer to the developer
            - if current_user
              = link_to "Delete", {:id => i.id, :controller => 'projectimages', :action => 'destroy'}, :method => :delete, data: {confirm: 'Do you want to delete #{i.name}?'}