config/routes.rb
Wolframpant::Application.routes.draw do
  devise_for :users
  resources :interests
  resources :events
  resources :images, only: [:show, :index, :new, :create, :destroy]
  resources :evints, only: [:new, :create, :destroy, :index]
  resources :projects, only: [:index, :edit, :update, :new, :create]
  resources :projectimages, only: [:show, :index, :new, :create, :destroy]
  get "welcome/index"
  root to: "welcome#index"
  # for resume
  get "welcome/readpdf"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wolframpant</title>
  <!-- Google Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Cinzel+Decorative|Federo|Fredericka+the+Great' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="container">
  <div class="epw">ELLEN P. WOLFSON</div>
  <!-- bootstrap classes -->
  <ul class="nav nav-tabs">
    <li><%= link_to "HOME", welcome_index_path %></li>
    <li><%= link_to "RESUME", '/Resume.pdf', :target => '_blank' %></li>
    <li><%= link_to "PORTFOLIO", projects_path %></li>
    <li><%= link_to "LINKEDIN PROFILE", "https://www.linkedin.com/in/wolframpant", :target => "_blank" %></li>
    <li><%= link_to "GITHUB PROFILE", "https://www.github.com/wolframpant", :target => "_blank" %></li>
    <li><%= mail_to "ellenpaulawolfson@gmail.com" %></li>

    <% if current_user %>
    <div class = "pull right">
    <%= link_to "Events", events_path %>
    <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
              <span class = "glyphicon glyphicon-log-out"></span> 
    <% end %>
    </div>
    <% end %>
  </ul>
     
  <% if flash[:notice] %>
    <p class="notices"><%= flash[:notice]%></p>
  <% end %>
    
  </div>

  <%= yield %>

  <script>$('body').flowtype();</script>
</body>
</html>